# Generated by Django 3.2.8 on 2021-10-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftar',
            name='tgl_kembali',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='daftar',
            name='tgl_pinjam',
            field=models.IntegerField(),
        ),
    ]
