# Generated by Django 3.2.8 on 2021-10-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0002_auto_20211021_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='pinjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmr_anggota', models.IntegerField()),
                ('nama', models.TextField(max_length=200)),
                ('buku', models.TextField(max_length=200)),
                ('jml_buku', models.IntegerField()),
                ('tgl_pinjam', models.IntegerField()),
                ('tgl_kembali', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='daftar',
        ),
    ]
