# Generated by Django 3.2.8 on 2021-10-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0004_auto_20211021_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjam',
            name='tgl_kembali',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pinjam',
            name='tgl_pinjam',
            field=models.DateField(blank=True, null=True),
        ),
    ]
